name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (with cache)
        if: hashFiles('package-lock.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Node (no cache)
        if: hashFiles('package-lock.json') == ''
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (ci if lockfile)
        if: hashFiles('package-lock.json') != ''
        run: npm ci
      - name: Install dependencies (no lockfile)
        if: hashFiles('package-lock.json') == ''
        run: npm install

      - name: Lint
        run: npm run lint
        env:
          CI: true

      - name: Test
        run: npm test --silent
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true
          NODE_OPTIONS: --max_old_space_size=4096
