name: Deploy newsletter-service to Cloud Run

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy-newsletter
  cancel-in-progress: true

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID || 'peppy-coda-471714-p7' }}
  REGION: ${{ vars.GCP_REGION || 'asia-northeast3' }}
  SERVICE: ${{ vars.CLOUD_RUN_SERVICE || 'newsletter-service' }}

jobs:
  deploy:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preflight check (require JSON key)
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "ERROR: Missing secret GCP_SA_KEY (Service Account JSON)." >&2
            exit 1
          fi

      - name: Auth to Google Cloud (JSON key)
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker auth for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build container image (Docker on runner)
        run: |
          REGISTRY=${{ env.REGION }}-docker.pkg.dev
          REPO=newsletter
          docker build -t $REGISTRY/${PROJECT_ID}/$REPO/${SERVICE}:${GITHUB_SHA} newsletter-service
          docker tag $REGISTRY/${PROJECT_ID}/$REPO/${SERVICE}:${GITHUB_SHA} $REGISTRY/${PROJECT_ID}/$REPO/${SERVICE}:latest

      - name: Push container image
        run: |
          REGISTRY=${{ env.REGION }}-docker.pkg.dev
          REPO=newsletter
          docker push $REGISTRY/${PROJECT_ID}/$REPO/${SERVICE}:${GITHUB_SHA}
          docker push $REGISTRY/${PROJECT_ID}/$REPO/${SERVICE}:latest

      - name: Deploy to Cloud Run
        run: |
          REGISTRY=${{ env.REGION }}-docker.pkg.dev
          REPO=newsletter
          gcloud run deploy ${SERVICE} \
            --image $REGISTRY/${PROJECT_ID}/$REPO/${SERVICE}:${GITHUB_SHA} \
            --platform managed --region ${REGION} --allow-unauthenticated \
            --set-env-vars SPRING_MAIL_HOST=smtp.sendgrid.net \
            --set-env-vars SPRING_MAIL_PORT=587 \
            --set-env-vars SPRING_MAIL_USERNAME=apikey \
            --set-env-vars SPRING_MAIL_PASSWORD=${{ secrets.SENDGRID_API_KEY }} \
            --set-env-vars app.mail.from=${{ vars.MAIL_FROM || 'no-reply@example.com' }} \
            --set-env-vars app.siteUrl=${{ vars.SITE_URL || 'https://ramsbaby.netlify.app' }} \
            --set-env-vars app.rssUrl=${{ vars.RSS_URL || 'https://ramsbaby.netlify.app/rss.xml' }}

      - name: Fetch Service URL
        id: run_url
        run: |
          URL=$(gcloud run services describe ${SERVICE} --region ${REGION} --format='value(status.url)')
          echo "url=${URL}" >> $GITHUB_OUTPUT

      - name: Set app.apiBaseUrl to Service URL
        run: |
          gcloud run services update ${SERVICE} --region ${REGION} \
            --set-env-vars app.apiBaseUrl=${{ steps.run_url.outputs.url }}

      - name: Summary
        run: |
          echo "Deployed to: ${{ steps.run_url.outputs.url }}" >> $GITHUB_STEP_SUMMARY


