name: Lighthouse CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Install Lighthouse CI
        run: npm i -g @lhci/cli@0.12.x
      - name: Run Lighthouse CI
        run: lhci autorun --upload.target=temporary-public-storage

